### ISSUE TITLE
Cannot get good results without edit mask and/or cached features

### ISSUE THREAD

**Issue by RuiningLi** [dangeng/motion_guidance#1]
Hi Daniel,

Nice work on motion guidance with diffusion models!

I have a question regarding the generation process. When trying to edit a real image, without specifying the mask, often I cannot get very good results (even for the images provided). What I did is e.g. `python ./generate.py --prompt "" --input_dir ./data/woman --target_flow_name growHair.pth --save_dir results/woman.growHair.no_mask --log_freq 5`. The generation usually doesn't change the source image very much. Can you share some insights on why this might happen? Am I doing something wrong?

Generation I get for the above execution:
![pred](https://github.com/dangeng/motion_guidance/assets/88520323/23532917-cb8a-4ba3-9675-06e05105729c)

Many thanks!
Ray

**Comment by dangeng** [comment]
Hey Ray,

Thanks for your interest! I took a look and it looks like there's a bug right [here](https://github.com/dangeng/motion_guidance/blob/8a550d81b7ea363fb1a1fd9358918ad26a748a6d/generate.py#L116). The mask is inverted from what it should be, which is why nothing is changing at all. I've pushed a [commit](https://github.com/dangeng/motion_guidance/commit/16c70a7ed93586e4101bc949343ff74d46b7c0b9), and hopefully it should work correctly now. Thanks for catching this!

P.S. By the way, in my experience the mask is fairly important to get good looking images. I think it's because otherwise the only way the model gets info about the source image pixels is through the color loss. This often results in the denoising trajectory roughly matching the colors, but not getting all the details correct. Using an edit mask, and injecting "hints" at each timestep for the model really improves the generation quality. It's possible messing with the loss and guidance weightings could helps as well, but I also found that this could lead to instability for weights that are too large.
