### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by KangLiao929** [dangeng/motion_guidance#5]
Hi Daniel,

Thanks for your interesting work. It inspired me a lot!

When I tried your code with my customized images and target flows, some weird results can be observed. In these cases, the foreground objects are expected to be enlarged horizontally. Please see the results below.

![results](https://github.com/user-attachments/assets/3022abe2-9d16-4a57-a3ed-7435278e30e0)

Could you please share any suggestions to solve them?

Many thanks!
Kang

**Comment by KangLiao929** [comment]
I also found such a 'flip' problem in your example when using 'stretchx' flow.

![xt 00495](https://github.com/user-attachments/assets/0ac5228e-a3a3-4fb5-af69-9e31bcf2f6ac)

**Comment by dangeng** [comment]
Hello, and thanks for your questions! I think you're probably running into limitations of our method, which we discuss in more detail in appendix A4. For example, the teapot is a problem with our method in which identity is not necessarily preserved. This is because there is nothing explicitly requiring the method to produce something that matches the identity--as long as RAFT will predict a close enough flow to the target flow, the guidance loss will be low.

The errors from the first image may come from the fact that the input images are out of distribution (they look a bit squished horizontally), and also that our method is fairly hard to tune. Likely, what you want to do is to increase the guidance loss weight to encourage the network to produce an image with the correct flow and with the correct pixel values. However, doing so too much will overly perturb the backward diffusion process and cause divergence and odd artifacts. We try many things in the paper to prevent this, including guidance scale scheduling, gradient clipping, and "recursive denoising." If you want to try to get better results you can fiddle around with any of these parameters.

I hope this makes things a bit clearer, and please let me know if you have any more questions!

**Comment by KangLiao929** [comment]
> Hello, and thanks for your questions! I think you're probably running into limitations of our method, which we discuss in more detail in appendix A4. For example, the teapot is a problem with our method in which identity is not necessarily preserved. This is because there is nothing explicitly requiring the method to produce something that matches the identity--as long as RAFT will predict a close enough flow to the target flow, the guidance loss will be low.
> 
> The errors from the first image may come from the fact that the input images are out of distribution (they look a bit squished horizontally), and also that our method is fairly hard to tune. Likely, what you want to do is to increase the guidance loss weight to encourage the network to produce an image with the correct flow and with the correct pixel values. However, doing so too much will overly perturb the backward diffusion process and cause divergence and odd artifacts. We try many things in the paper to prevent this, including guidance scale scheduling, gradient clipping, and "recursive denoising." If you want to try to get better results you can fiddle around with any of these parameters.
> 
> I hope this makes things a bit clearer, and please let me know if you have any more questions!

Thanks for your detailed reply! I am much clearer now. 

I was involved in a project that aims to recover the original shape of objects in a horizontally resized image. Thus, I wanted to use a 'stretch_x'-like flow with your motion guidance model. For the teapot case, the result presented in your paper looks reasonable, which keeps the same direction as the original input:

![image](https://github.com/user-attachments/assets/becb44c4-d004-4f16-b1d1-a6a0a44aa1c7)

However, my reproduced results show while the shape has been recovered, the direction of the edited object always be opposite to the input (as shown in the above comments). May I ask did you encounter similar results in your experiments?

**Comment by dangeng** [comment]
If it's always the opposite direction that is a bit surprising. I remember the direction would occasionally switch, but the edit mask and the flow constraints should be guiding the sampling so that the handle is on the correct side. Perhaps try playing with the guidance weights?
